CREATE TABLE TBL_AUTHORITIES
  (
     USERNAME  VARCHAR2(20),
     AUTHORITY VARCHAR2(20),
     CONSTRAINT TBL_AUTHORITIES_PK PRIMARY KEY (USERNAME, AUTHORITY)
  )
TABLESPACE ORA_DATA01;

CREATE TABLE TBL_GROUP
  (
     GROUP_ID   VARCHAR2(20),
     GROUP_NAME VARCHAR2(20),
     CONSTRAINT IDX_TBL_GROUP_PK PRIMARY KEY (GROUP_ID)
  )
TABLESPACE ORA_DATA01;

CREATE TABLE TBL_GROUP_AUTHORITIES
  (
     GROUP_ID  VARCHAR2(20),
     AUTHORITY VARCHAR2(20),
     CONSTRAINT TBL_GROUP_AUTHORITIES_PK PRIMARY KEY (GROUP_ID, AUTHORITY)
  )
TABLESPACE ORA_DATA01;

CREATE TABLE TBL_GROUP_MEMBERS
  (
     GROUP_ID VARCHAR2(20),
     USERNAME VARCHAR2(20),
     CONSTRAINT TBL_GROUP_MEMBERS_PK PRIMARY KEY (GROUP_ID, USERNAME)
  )
TABLESPACE ORA_DATA01;

CREATE TABLE TBL_USERS
  (
     USERNAME VARCHAR2(20),
     PASSWORD VARCHAR2(100),
     ENABLED  NUMBER(*, 0),
     CONSTRAINT IDX_TBL_USERS_PK PRIMARY KEY (USERNAME)
  )
TABLESPACE ORA_DATA01;

CREATE TABLE TB_ROLES
  (
     AUTHORITY   VARCHAR2(50) NOT NULL ENABLE,
     ROLE_NAME   VARCHAR2(100),
     DESCRIPTION VARCHAR2(100),
     CREATE_DATE DATE,
     MODIFY_DATE DATE,
     CONSTRAINT PK_ROLES PRIMARY KEY (AUTHORITY)
  )
TABLESPACE ORA_DATA01;

CREATE TABLE TB_SECURED_RESOURCES
  (
     RESOURCE_ID      VARCHAR2(50) NOT NULL ENABLE,
     RESOURCE_NAME    VARCHAR2(50),
     RESOURCE_PATTERN VARCHAR2(300) NOT NULL ENABLE,
     DESCRIPTION      VARCHAR2(100),
     RESOURCE_TYPE    VARCHAR2(10),
     SORT_ORDER       VARCHAR2(10),
     CREATE_DATE      DATE,
     MODIFY_DATE      DATE,
     CONSTRAINT PK_RECURED_RESOURCES PRIMARY KEY (RESOURCE_ID)
  )
TABLESPACE ORA_DATA01;

CREATE TABLE TB_USERS
  (
     USERNAME VARCHAR2(50) NOT NULL ENABLE,
     PASSWORD VARCHAR2(50) NOT NULL ENABLE,
     ENABLED  NUMBER(*, 0) NOT NULL ENABLE,
     CONSTRAINT PK_USERS PRIMARY KEY (USERNAME)
  )
TABLESPACE ORA_DATA01;

CREATE TABLE TB_AUTHORITIES
  (
     USERNAME  VARCHAR2(50) NOT NULL ENABLE,
     AUTHORITY VARCHAR2(50) NOT NULL ENABLE,
     CONSTRAINT PK_AUTHORITIES PRIMARY KEY (USERNAME, AUTHORITY)
  )
TABLESPACE ORA_DATA01;

CREATE TABLE TB_ROLES_HIERARCHY
  (
     PARENT_ROLE VARCHAR2(50) NOT NULL ENABLE,
     CHILD_ROLE  VARCHAR2(50) NOT NULL ENABLE,
     CONSTRAINT PK_ROLES_HIERARCHY PRIMARY KEY (PARENT_ROLE, CHILD_ROLE)
  )
TABLESPACE ORA_DATA01;

CREATE TABLE TB_SECURED_RESOURCES_ROLE
  (
     RESOURCE_ID VARCHAR2(50) NOT NULL ENABLE,
     AUTHORITY   VARCHAR2(50) NOT NULL ENABLE,
     CREATE_DATE DATE,
     CONSTRAINT PK_SECURED_RESOURCES_ROLE PRIMARY KEY (RESOURCE_ID,
     AUTHORITY)
  )
TABLESPACE ORA_DATA01; 
